name: facenet-demo
channels:
- defaults
dependencies:
- h5py=2.7.0
- hdf5=1.8.15.1
- mkl=2017.0.3
- pip=9.0.1
- python=3.6.2
- scipy=0.19.1
- six=1.10.0
- zlib=1.2.11
- pip:
  - flask==0.12.2
  - Keras==2.1.4
  - keras_vggface==0.5
  - numpy==1.14.1
  - Pillow==5.0.0
  - python-resize-image==1.1.11
  - scikit-learn==0.19.1
  - tensorflow-gpu==1.6.0rc1
