name: facenet-demo
channels:
- defaults
dependencies:
- certifi=2016.2.28
- h5py=2.7.0
- hdf5=1.8.15.1
- mkl=2017.0.3
- numpy=1.13.1
- pip=9.0.1
- python=3.6.2
- scipy=0.19.1
- setuptools=36.4.0
- six=1.10.0
- zlib=1.2.11
