name: facenet-demo
channels:
- defaults
dependencies:
- certifi=2016.2.28
- h5py=2.7.0
- hdf5=1.8.15.1
- mkl=2017.0.3
- numpy=1.14.1
- pip=9.0.1
- python=3.6.2
- scipy=0.19.1
- six=1.10.0
- zlib=1.2.11
- pip:
  - Keras==2.1.4
  - keras_vggface==0.5
  - Pillow==5.0.0
  - tensorflow-gpu==1.6.0rc1
  - flask==0.12.2
